# Generated by Django 5.0.8 on 2024-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='classificacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
