# Generated by Django 5.0.8 on 2024-08-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='em_espera',
            field=models.BooleanField(default=False),
        ),
    ]
