# Generated by Django 5.0.8 on 2024-08-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_aluno_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='vagas_disponiveis',
            field=models.IntegerField(default=0),
        ),
    ]
